# Site settings
author: Sarah Rogers
title: 
header-img: img/home-bg.png
email: s.rogers0715@yahoo.com
copyright_name: Sarah Rogers
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Srog1989

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
